ports:
  - name: Kurento
    description: WebRTC Media Server
    port: 8888
    onOpen: ignore
  - name: Tutorial App
    description: Web app generating a media stream
    port: 8443
    onOpen: open-preview