version: "3"

services:

  kurento-examples:
    image: fiware/kurento-examples
    container_name: examples-kurento
    depends_on:
      - kurento
    build: 
      context: ../kurento-examples
      dockerfile: Dockerfile
    ports:
      - 8443:8443
    networks:
      - default
    environment:
      - "MEDIA_SERVER_HOST=kurento"
      - "MEDIA_SERVER_PORT=8888"
      - "APP_SERVER_HOST=kurento-examples"
      - "APP_SERVER_PORT=8443"
      - "TUTORIAL_NAME=${TUTORIAL_NAME}"

  kurento:
    image: fiware/stream-oriented-kurento
    hostname: kurento
    container_name: fiware-kurento
    expose:
      - "8888"
    ports:
      - 8888:8888
    networks:
      - default

networks:
  default:
     