version: "3.8"

services:
  kurento-examples:
    labels:
      org.fiware: 'tutorial'
    image: quay.io/fiware/kurento-examples
    container_name: examples-kurento
    depends_on:
      - kurento
    build:
      context: ../kurento-examples
      dockerfile: Dockerfile
    ports:
      - 8443:8443
    networks:
      - default
    environment:
      - "MEDIA_SERVER_HOST=kurento"
      - "MEDIA_SERVER_PORT=8888"
      - "APP_SERVER_HOST=kurento-examples"
      - "APP_SERVER_PORT=8443"
      - "TUTORIAL_NAME=${TUTORIAL_NAME}"

  kurento:
    labels:
      org.fiware: 'tutorial'
    image: kurento/kurento-media-server-plus-filters
    hostname: kurento
    container_name: fiware-kurento
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8888"
    ports:
      - 8888:8888
    networks:
      - default

networks:
  default:
    labels:
      org.fiware: 'tutorial'
    ipam:
      config:
        - subnet: 172.18.1.0/24
